- src/api/snapshotApi.ts
- src/components/Voting/VotingCard.tsx
- src/components/Voting/VotingStatusFilter.tsx
- src/components/__tests__/__snapshots__/VotingCard.test.tsx.snap
- src/components/__tests__/__snapshots__/VotingStatusFilter.test.tsx.snap
- src/models/voting.ts
- src/pages/voting/[votingSlug].tsx
- src/pages/voting/index.tsx
Changes are 
* Snapshot query - Fetching scores and choices from snapshot API to determine winning choice (src/api/snapshotApi.ts)
* Model - To account for the additional fields (src/models/voting.ts)
* Display - Determination of the status tag to display (src/components/Voting/VotingCard.tsx, src/pages/voting/[votingSlug].tsx)
* Test update
-
-
- Resolves [#16](https://github.com/new-order-network/new-order-app-ui/issues/16)
> feat: update the voting card status tag to show result of the snapshot

- src/components/VeNewo/LockedToken.tsx
- src/hooks/useVeToken.ts
- src/pages/venewo.tsx
- add the exit function on the useVeToken hook
- add parameters to LockedToken component
-
-
- Resolves #33
> fix: add the fucntion to withdraw all locked tokens

- src/components/Vault/ActiveDeposit.tsx
- src/components/Vault/Vault.tsx
- src/components/Vault/VeActiveDeposit.tsx
- src/components/Vault/VeVault.tsx
- src/components/VeNewo/LockForm.tsx
- src/components/VeNewo/LockedToken.tsx
- src/components/VeNewo/Position.tsx
- src/components/VeNewo/RegisteredReward.tsx
- src/components/VeNewo/RegistrationReward.tsx
- src/components/WalletWidget/AddressButton.tsx
- src/components/WalletWidget/NetworkButton.tsx
- src/components/WalletWidget/WalletWidget.tsx
- src/hooks/useAirdrop.ts
- src/hooks/useGovernanceVault.ts
- src/lib/utils/web3.ts
- src/pages/airdrops.tsx
- src/pages/venewo.tsx
- src/pages/voting/[votingSlug].tsx
- src/pages/voting/index.tsx
- src/store/contexts/contractContext.tsx
- src/store/contexts/newoContext.tsx
- src/store/contexts/veNewoContext.tsx
- src/store/contexts/votingContext.tsx
- lessen infinite logs causing it to crash
---
- https://app.asana.com/0/0/1203273170853422
- https://app.asana.com/0/0/1203277982270864
> fix: app crash when trying to change network

- src/hooks/useAirdrop.ts
- src/hooks/useGovernanceVault.ts
- src/hooks/useToken.ts
- src/hooks/useVault.ts
- src/hooks/useVeToken.ts
- src/hooks/useVeVault.ts
- src/pages/invest.tsx
- src/pages/venewo.tsx
- restructured the way to set token instance
- fix claim function
- remove `isLazy` prop on `Tabs` component
- image to show pending transaction on metamask
---
- https://app.asana.com/0/0/1203285099930615
> fix: claim function on venewo rewards and vaults

- src/components/VeNewo/LockForm.tsx
- add the `updateState` function when the approval function is finished
- Would be nice to merge #42 first to see this in action
---
- https://app.asana.com/0/0/1203320607117039
> fix: disable venewo button after approval function

- src/components/WalletWidget/WalletWidget.tsx
- src/pages/invest.tsx
- src/store/contexts/newoContext.tsx
- src/store/reducers/newoReducer.ts
- [fix: hydration message on header components](https://github.com/new-order-network/new-order-app-ui/commit/1b5c1339f5dea908cdb2585e67e43f71cf627215)
- [fix: hydration message on invest page](https://github.com/new-order-network/new-order-app-ui/commit/98d6b91f6f56f6e7a3e88c341fa4afbab1c31601)
-
-
-
---
- https://app.asana.com/0/0/1203277982270869
> fix: hydration error messages

- src/pages/voting/[votingSlug].tsx
- src/pages/voting/index.tsx
- src/store/contexts/votingContext.tsx
- src/store/reducers/votingReducer.ts
- add voting power on voting page
---
- https://app.asana.com/0/0/1203749103971702
> feat: show voting power on voting page

- src/pages/voting/[votingSlug].tsx
> fix: incorrect voting completion date

- package.json
- src/components/VeNewo/Claim.tsx
- src/components/VeNewo/Locker.tsx
- src/constants/network.ts
- src/lib/utils/venewo.ts
- src/lib/utils/web3.ts
- src/pages/_app.tsx
- src/pages/api/venewo/index.ts
- src/pages/venewo.tsx
- src/store/contexts/veNewoContext.tsx
- src/store/contexts/votingContext.tsx
- yarn.lock
- fix errors related to changes from the dependency
-
- **WIP**: trying to fix a bug related to gnosis and its walletconnect app
> chore: update wagmi dependency to latest version

- src/components/Voting/VotingPower.tsx
- src/pages/_app.tsx
- src/pages/voting/index.tsx
- remove voting provider on `_app.tsx`
> refactor: move the voting context provider to voting related pages

- .github/dependabot.yml
- added `dependabot.yml` file on .github folder
> chore: add dependabot on github actions

- src/components/VeNewo/LockForm.tsx
- src/components/WalletWidget/AddressButton.tsx
- src/constants/contractAddresses.ts
- src/lib/utils/format.ts
- src/models/web3.ts
- src/store/contexts/newoContext.tsx
- src/store/reducers/newoReducer.ts
- `useBalance` to fetch the balance of `NEWO`
- change the dispatch functions available on the newo context
- modify formatting functions
> refactor: use wagmi hook to fetch newo balance

- src/constants/externalLink.ts
- src/constants/voting.ts
- src/pages/index.tsx
- src/pages/voting/index.tsx
- src/store/contexts/votingContext.tsx
- remove the governance staking button
- update community link to use new order academy
- refactor calculation of the voting power
---
- https://app.asana.com/0/0/1203975401435401
> chore: remove governance staking button and modal

- src/middleware.ts
- src/pages/not-available.tsx
- add a `not-available` page
- block US countries
> feat: add geoblocking for US countries

- src/hooks/useVeVault.ts
- change `veVaultInstance` to use the hook from wagmi
> refactor: add gas limit to functions on the veVault hook

- src/components/Vault/VeActiveDeposit.tsx
- src/components/Vault/VeVault.tsx
- src/components/VeNewo/LockForm.tsx
- src/components/VeNewo/RegisteredReward.tsx
- src/components/VeNewo/RegistrationReward.tsx
- src/hooks/useToken.ts
- src/hooks/useVeToken.ts
- src/hooks/useVeVault.ts
- src/lib/utils/vault.ts
- src/middleware.ts
- src/pages/invest.tsx
- src/store/contexts/contractContext.tsx
- src/store/contexts/newoContext.tsx
- src/store/contexts/veNewoContext.tsx
- refactor `useVeVault` (remove `useVault` inside hook to reduce data fetched, use `wagmi` hooks to fetch data)
- remove console warnings about failed balance data
> fix: venewo balance missing on the venewo page for avalanche

- src/components/VeNewo/LockedToken.tsx
- src/store/contexts/veNewoContext.tsx
- prevents users to withdraw right away
- informs users about claimable `NEWO`
> feat: add warning when a user withdraws from venewo

- src/components/Vault/ActiveDeposit.tsx
- src/components/Vault/Vault.tsx
- src/components/Vault/VeActiveDeposit.tsx
- src/components/Vault/VeVault.tsx
- [feat: disable deposit with 0% APR for LP Vaults](https://github.com/new-order-network/new-order-app-ui/commit/710356be1d53c3746ad3fb6feaff0b4d7d6edc7a)
- [feat: disable withdraw & claim if there are no rewards](https://github.com/new-order-network/new-order-app-ui/commit/036d62e56ef4617373c1a5b17b4043817253b1f9)
---
- https://app.asana.com/0/0/1204601839784569
- https://app.asana.com/0/0/1204601839784573
> feat: disable buttons

- src/components/VeNewo/AirdropReward.tsx
- src/components/VeNewo/Claim.tsx
- src/components/VeNewo/LockForm.tsx
Other changes
- [feat(style): update button alignment](https://github.com/new-order-network/new-order-app-ui/pull/106/commits/46a14135dad7e03918490b911828172caf17d9f9)
> chore: temporarily hide step 3 on venewo page

- src/components/VeNewo/AirdropReward.tsx
- src/components/VeNewo/Claim.tsx
> feat: show APR

- src/components/VeNewo/AirdropReward.tsx
- src/hooks/useVeAirdropReward.ts
---
- https://app.asana.com/0/0/1204661416959775
> feat: add alert message if vault is currently under maintenance

- src/constants/vaults.ts
> refactor: remove ve LP vaults

- src/components/VeNewo/Locker.tsx
- remove contracts on locker tab
> refactor: remove ve LP vault

- src/components/VeNewo/AirdropReward.tsx
- [refactor: remove ve LP vaults](https://github.com/new-order-network/new-order-app-ui/commit/b50a030733e65a83681a610b6a44575858cbce92)
- refactor: remove ve LP vault contract on locker tab
> dev changes [06.12.2023]

- src/components/VeNewo/AirdropReward.tsx
> fix(update): update airdrop rewards info text

- src/hooks/useVeAirdropReward.ts
> feat(fix): fix airdrop

- src/components/VeNewo/Claim.tsx
> feat(update): airdrop eth

- src/components/VeNewo/LockedToken.tsx
> feat(update): allow to withdraw even if unlock date is not reached

- src/components/VeNewo/LockedToken.tsx
> feat(fix): remove modals

- src/components/VeNewo/LockedToken.tsx
> Withdraw veNEWO fix

- src/components/VeNewo/AirdropReward.tsx
> feat(fix): update

- src/constants/sidebarMenu.ts
> feat: delegation

- src/components/VeNewo/LockedToken.tsx
- src/constants/sidebarMenu.ts
> dev -> main
